#!/bin/zsh

# Routine session variables: such that files that have been imported already 
# won't be included again. 
[ -z "$hq_imprtd_sssn" ] && local hq_imprtd_sssn=""
[ -z "$hq_imprtd_cnt" ] && local hq_imprtd_cnt=1 || (( hq_imprtd_cnt+=1 )) 

# Set package name, since it's not easily inferred once this file is called 
# @todo:reevaluate - latest implemenations made this redundant?
local _name="hq-cli-util"

# Set the file to be sourced path: part of HQ_IMPORTER file path and desired 
# suffix 
local _path="${HQ_IMPORTER%/$_name/*}/$_name/src/$1"
if [[ $hq_imprtd_sssn != *$_path* ]]; then
	hq_imprtd_sssn+=" $_path"
	shift
	source "$_path"
fi

