#!/bin/zsh

# All utility functions in this file relate solely to date; no time related
# logic or results. The sibling "datetime" utility file is your want if so.
# Alternatevily make use of the "time" utility file.

date__now() {
  echo $(date +%d/%m/%y)
}

date__now_seconds() {
  echo $(date -u +%s)
}
