#!/bin/zsh

source $HQ_IMPORTER system
source $HQ_IMPORTER array
source $HQ_IMPORTER ensure

dir__was_changed(){
	system__not_implemented
}

dir__name(){
	ensure__n_args 1 $@
	local name=
	local result=
	name=$(basename "$1")
	result=$?

	echo $name
	return $result
}

# @todo:coverage - test for directories with spaces.
dir__changed_files(){
	local saved_dir=$(pwd)
	local target_dir=$1
	local start_time=$2
	local excludes_n=$(array__size $3)
	local excludes_str=""
	if [ "$excludes_n" -gt "0" ]; then 
		# Create exclude part of the find command. It follows this format:
		# find . -not \( -path "./excluded_dir/" -prune\). 
		# This syntax and optionology makes find avoid recursive looks into a folder
		# content.
		excludes_str=$(array__concat $3 "-not ( -path ./" " -prune ) ")
	fi

	local current_time=$(datetime__now)
	local diff_mins=$(datetime__diff__mins $current_time $start_time)

	cd $target_dir
	# Option "-mmin -<amount_of_mins>" gets files that where changed since
	# <amount_of_mins> ago. 
	local find_cmd="find . -mmin -$diff_mins -type f $excludes_str"
	echo $(${=find_cmd})
	cd $saved_dir
}
