#!/bin/zsh

hq_importer ensure

echoing__get() {
  local echoing=0
  (system__echo_or_not "$@")
  echoing=$?
}

# @Frost
# - Replace this (if and echo)
# [[ $echoing == 1 ]] &&
#     echo "Nothing found for \"${config}\""
# - With this (something alike; 1 liner)
# echoing "Nothing found for \"${config}\""

red="\e[1;31m%s\e[0m\n"
green="\e[1;32m%s\e[0m\n"
yellow="\e[1;33m%s\e[0m\n"

echoing__red () {
	#ensure__n_args "$@" 1 # TODO - does not work 
	printf "$red" "$1"
}
