#!/bin/zsh

git__get_branch() {
  # Todo - overkill
  git branch 2>/dev/null | sed -n -e 's/^\* \(.*\)/\1/p'
  # git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
  # ?? #!/usr/bin/env ruby
  # git for-each-ref --format=' %(authorname) %09 %(refname)' --sort=authorname
}

git__is_dir_repo() {
  # Todo - accepted arg with path to be checked (if is within a repo)
  # instead of being automatically the current folder
  git rev-parse --is-inside-work-tree >/dev/null 2>&1
  return $?
}
