#!/bin/zsh

source $HQ_IMPORTER system
source $HQ_IMPORTER string
source $HQ_IMPORTER dir

local HQ_CONST__PROFILE_PATH=~/.profile
local HQ_CONST__ZPROFILE_PATH=~/.zprofile
local HQ_CONST__BASHRC_PATH=~/.zprofile


pkg__register_path() {
	__pkq__ensure_in_profile "export PATH=\"$(this__pwd)/bin:\$PATH\""
}

pkg__register_HQ_env () {
	__pkq__ensure_in_profile "export HQ_=\"$HQ_IMPORTER\""
}

# @todo - deprecate for HQ_ instead?
pkg__register_HQ_IMPORTER_env () {
	__pkq__ensure_in_profile "export HQ_IMPORTER=\"$HQ_IMPORTER\""
}

pkg__register_propmt_command(){
}

__pkg__ensure_in_profile(){
	ensure__n_args 1
	# @todo:required ensure zprofile, aborts if non existent 
	# as it doesnt support bash...
	# - ensure should/could cache existence of files?? if on sae call stack ish ??
	local profile_file=$HQ_CONST__PROFILE_PATH
	local shell_type=$(echo $0)

	# If on a zsh terminal, overwrites the target zprofile file
	string__contains $shell_type "zsh" && profile_file=$HQ_CONST__ZPROFILE_PATH

	file__ensure_content profile_file $1
}

pkg__get_profile_path(){
	
}

pkg__install(){
	echo "in pkg__install"
	local BIN_FILE=bin/"${PWD##*/}"
	echo $BIN_FILE
	ensure__or_mkdir bin
	touch $BIN_FILE
	echo "#!/bin/zsh" > $BIN_FILE
}

#TODOc - Copied / Powerful / Complex
# exec sudo --login --user "$USER" /bin/sh -c "cd '$PWD'; exec '$SHELL' -l"
